version: "3.7"

services:
  mongo_db:
    build: ./mongodb 
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOCAL_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_LOCAL_PASSWORD}
      MONGO_INITDB_DATABASE: schedule_db
      MONGO_LOCAL_HOST: ${MONGO_LOCAL_HOST}
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
    networks:
      backend_network:
        ipv4_address: 10.9.0.3

  backend_server:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/go/src/app/logs  # Mount the logs directory
    networks:
      backend_network:
        ipv4_address: 10.9.0.2 

  db_init_container: 
    build: ./mongodb/scripts
    depends_on:
      - mongo_db
    environment: 
      MONGO_LOCAL_HOST: ${MONGO_LOCAL_HOST}
      MONGO_LOCAL_USERNAME: ${MONGO_LOCAL_USERNAME}
      MONGO_LOCAL_PASSWORD: ${MONGO_LOCAL_PASSWORD}
    ports: 
      - "9000:9000" 
    networks:
      backend_network: 
        ipv4_address: 10.9.0.4

networks:
  backend_network:
    name: backend_network
    ipam:
      config:
        - subnet: 10.9.0.0/24