version: "3.7"

services:
  mongo_db:
    build: ./mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: schedule_db
      MONGO_ADDRESS: ${MONGO_ADDRESS}
      MONGO_PORT: ${MONGO_PORT}
    ports:
      - "27017:27017"
    networks:
      backend_network:
        ipv4_address: 10.9.0.3

  backend_server:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/go/src/app/logs  # Mount the logs directory
    networks:
      backend_network:
        ipv4_address: 10.9.0.2

networks:
  backend_network:
    name: backend_network
    ipam:
      config:
        - subnet: 10.9.0.0/24