name: Docker Image CI

on:
  push:
    branches: [ "dev" ,"C2-29-Implement-GitHub-Actions" ]
  pull_request:
    branches: [ "dev" ]

jobs: 

  create_env: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v3 
      - name: Create the .env file needed for compose
        run: | 
          cd /home/runner/work/Backend/Backend/
          echo "${{ secrets.ENV_FILE }}" > .env
          

  build:

    runs-on: ubuntu-latest
    steps:
       # need checkout before using compose-action
       - uses: actions/checkout@v3
       - uses: isbang/compose-action@v1.4.1
         with:
          compose-file: "docker-compose.yml" 
          up-flags: "--build"
