# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs: 

 start-up-docker: 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v3 
    - name: start backend  
    - run: echo ${{ secrets.ENV_FILE }} > .env
    - run: docker-compose up --build -d

 build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
