# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs: 

  run-docker: 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v3 
    - run: echo "${{ secrets.ENV_FILE }}" > .env   
    - run: docker-compose up --build -d 
    - uses: actions/setup-go@v3 
      with: 
        go-version: 1.19 
    - run: go build -v ./... 
    - run: go test -v ./...  
    - uses: actions/checkout@v3
    - run: docker-compose down
